//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PassengerTransportationProject.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PassengerTransportationEntities : DbContext
    {
        public PassengerTransportationEntities()
            : base("name=PassengerTransportationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Gender> Gender { get; set; }
        public virtual DbSet<MyTicket> MyTicket { get; set; }
        public virtual DbSet<Nationality> Nationality { get; set; }
        public virtual DbSet<Passenger> Passenger { get; set; }
        public virtual DbSet<Position> Position { get; set; }
        public virtual DbSet<Route> Route { get; set; }
        public virtual DbSet<StationDeparture> StationDeparture { get; set; }
        public virtual DbSet<StationTarget> StationTarget { get; set; }
        public virtual DbSet<Task> Task { get; set; }
        public virtual DbSet<Transporter> Transporter { get; set; }
    }
}
